
GET http://localhost:3000/events

###
GET http://localhost:3000/events/cdfb5551-5ffa-437d-871a-7a744fef7dde

###
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Event New",
  "date": "2021-03-03T00:00:00",
  "price": 125,
  "description": "This is a new event"
}

###
PATCH http://localhost:3000/events/cdfb5551-5ffa-437d-871a-7a744fef7dde
Content-Type: application/json

{
  "name": "Event Old",
  "date": "2021-03-03T00:00:00",
  "price": 125,
  "description": "This is a new event"
}

###
DELETE http://localhost:3000/events/313fc4d5-acc6-4bc9-8305-92b154aa8fa8


SPOTS

###
POST http://localhost:3000/events/cdfb5551-5ffa-437d-871a-7a744fef7dde/spots
Content-Type: application/json

{
  "name": "A2"
}

###
GET http://localhost:3000/events/cdfb5551-5ffa-437d-871a-7a744fef7dde/spots


RESERVAR

###
POST http://localhost:3000/events/cdfb5551-5ffa-437d-871a-7a744fef7dde/reserve
Content-Type: application/json

{
  "spots": ["A1", "A2"],
  "ticket_kind": "full",
  "email": "test@test.com"
}